### ISSUE TITLE
fix for 3.10

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbwidgets#210]
collections has no attribute Mapping

**Comment by weiglszonja** [comment]
`ipyvolume==0.6.0a10;python_version>='3.10' `
this fixes that error however this is not the only thing that is required to fix for `3.10`:

`ipysheet 0.5.0` is incompatible with `ipywigets 8.x` and looks the issue that @oruebel opened has not been resolved:
https://github.com/QuantStack/ipysheet/issues/231
https://github.com/NeurodataWithoutBorders/nwbwidgets/issues/220
I figured out how to resolve that with using @widgets.register instead of @widgets.register('ipysheet.Sheet'), but the tests are still not passing. Now I have something else:

```
        backend_mod = importlib.import_module(
            cbook._backend_module_name(newbackend))
>       canvas_class = backend_mod.FigureCanvas
E       AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'
```

/Users/weian/opt/anaconda3/envs/nwbwidgets/lib/python3.10/site-packages/matplotlib/pyplot.py:266: AttributeError

It looks like there is still a package incompatibility issue yet to be solved, but not sure how to proceed.
I have `matplotlib-3.6.0`

**Comment by bendichter** [comment]
@weiglszonja is it just ipysheet causing the issue? Perhaps we could replace that with something else like draw the table ourselves in HTML?

**Comment by weiglszonja** [comment]
Yes, if that issue is fixed we should be good to go. I opened a [PR](https://github.com/QuantStack/ipysheet/pull/233) there, until it is merged, maybe we can pin the ipysheet version to it to double-check it is all that is needed? 
besides `ipyvolume==0.6.0a10;python_version>='3.10'`

**Comment by martinRenou** [comment]
Hi, sorry to come here uninvited 

```
         backend_mod = importlib.import_module(
            cbook._backend_module_name(newbackend))
>       canvas_class = backend_mod.FigureCanvas
E       AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'
/Users/weian/opt/anaconda3/envs/nwbwidgets/lib/python3.10/site-packages/matplotlib/pyplot.py:266: AttributeError
```

I may be wrong but I believe it's unlikely ipysheet is the culprit for this error, as ipysheet is not using Matplotlib.

> Perhaps we could replace that with something else

If you just want to draw a table, I can suggest looking at [ipydatagrid](https://github.com/bloomberg/ipydatagrid) which is more performant than ipysheet.

Also ipysheet depends on an old unmaintained version of Handsontable (Handsontable is not open-source anymore), so it won't get updated so often now. This issue was one of the reasons to start creating ipydatagrid.

**Comment by weiglszonja** [comment]
@martinRenou Thank you for letting us know! 

> I may be wrong but I believe it's unlikely ipysheet is the culprit for this error, as ipysheet is not using Matplotlib.

Yeah sorry, I figured out that was unrelated to `ipysheet`.

I'll be looking into `ipydatagrid`, looks great! 👀
